services:
  dyna-photosite:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dyna-photosite
    restart: unless-stopped

    ports:
      - "3000:3000"

    volumes:
      - ./data:/data

